//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emp
    {
        public int e_iD { get; set; }
        public string e_Name { get; set; }
        public int Age { get; set; }
        public string Address { get; set; }
        public int Phone { get; set; }
        public int Nid { get; set; }
    }
}
