// <auto-generated />
namespace AuthenticationTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatetbl_empforreporting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetbl_empforreporting));
        
        string IMigrationMetadata.Id
        {
            get { return "201703200421199_update tbl_emp for reporting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
