// <auto-generated />
namespace AuthenticationTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedroles_actiontabletodaynow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedroles_actiontabletodaynow));
        
        string IMigrationMetadata.Id
        {
            get { return "201703161141516_added roles_action table today now"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
